### ISSUE TITLE
rbenv install not working with proxy :(

### ISSUE THREAD

**Issue by emarashliev** [sstephenson/rbenv#652] opened 2014-11-13 14:18 UTC
Me using proxy for all my traffic and when I'm trying to install new ruby version become some kind of disaster! I have proxy setup for wget and curl, but obviously rbenv doesn't use any of these. Can you please tell me how rbenv downloading ruby sources?

**Comment by mislav** [comment] 2015-01-13 19:47
Closing this due to lack of info. If you're still having problems and you're pretty sure our proxy support is broken, can you please open an issue on the ruby-build project. Thanks

**Closed by mislav** 2015-01-13 19:47 UTC
Labels: ruby-build

**Comment by cisolarix** [comment] 2015-06-17 03:12
`http_proxy=` works for me on Yosemite

**Comment by meysammeisam** [comment] 2016-01-13 15:18
`ALL_PROXY` worked here :+1:

**Comment by georgeuy** [comment] 2016-05-11 13:17
ALL_PROXY worked fine to me

`salgest@salgest6:~$ rbenv install 2.3.1
Downloading ruby-2.3.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
error: failed to download ruby-2.3.1.tar.bz2

BUILD FAILED (Ubuntu 16.04 using ruby-build 20160426-12-gf03f7f8)

salgest@salgest6:~$ ALL_PROXY=http://127.0.0.1:3128 rbenv install 2.3.1
Downloading ruby-2.3.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
Installing ruby-2.3.1...`

Thanks

**Comment by Joelith** [comment] 2016-07-28 02:53
setting HTTPS_PROXY worked for me (OEL 6.8)

**Comment by tlesso** [comment] 2017-05-26 18:53
I was able to reproduce this behavior on Ubuntu 16.04. The problem is in [rbenv/ruby-build/blob/master/bin/ruby-build](https://github.com/rbenv/ruby-build/blob/master/bin/ruby-build) - line 333, which says 

> curl -q -o "${2:--}" -sSLf ${CURL_OPTS} "$1"

This tells curl to ignore the `.curlrc` file where a proxy may be located, given that in Ubuntu curl doesn't seem to pay attention to `HTTP_PROXY`, http_proxy, etc. I was able to work past this problem by setting the `RUBY_BUILD_CURL_OPTS` environment variable to include curl options of `--proxy http://proxyname.proxy:80/`. Note the port number specified is 80, since in my case the default curl proxy port seems to be 1080.

**Comment by pbures** [comment] 2017-08-09 09:45
Also you may be hitting a problem with curl, not negotiating the SSL/TLS connections right. Verify that you can download the ruby archive from https via curl. If not and you get an error:
_curl: (35) Peer reports incompatible or unsupported protocol version._
then you are hitting the ssl/tls issue, see https://bugzilla.redhat.com/show_bug.cgi?id=1170339

A solution is to:
> export RUBY_BUILD_CURL_OPTS=--tlsv1

**Comment by flenny** [comment] 2018-11-08 12:57
The following command worked for me on Ubuntu 18.04 with a proxy with SSL interception
`ALL_PROXY=http://proxy:8080 RUBY_BUILD_CURL_OPTS=-k rbenv install 2.5.1`

**Comment by kapoorlakshya** [comment] 2018-12-10 23:55
I'm using Windows Subsystem for Linux on Windows 10 and none of the commands shared above work for me. All throw this error:

```
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
error: failed to download ruby-2.5.3.tar.bz2

BUILD FAILED (Ubuntu 18.04 using ruby-build 20181207)
```
I am able to `curl` the `ruby-2.5.3.tar.bz2` file with the `http_proxy` var defined in `.curlrc` though. Not sure why `rbenv` is not using the proxy.

**Comment by wellington1993** [comment] 2021-06-30 00:59
Like @flenny, I used that command:

```RUBY_BUILD_CURL_OPTS=--insecure rbenv install 1.8.7-p374 -vvv```

To bypass SSL cert validation in Curl for Rbenv.

**Comment by hxhxd** [comment] 2022-02-17 10:18
`ALL_PROXY=socks5://ip:port rbenv install 3.1.0`
worked for me.
