### ISSUE TITLE
$PATH has shims directory last after reboot

### ISSUE THREAD

**Issue by deiga** [sstephenson/rbenv#635] opened 2014-10-13 05:12 UTC
Recently I have been getting strange behaviour after reboots, so that my shims directory ends up last on path and rbenv virtually unusable. Restarting my terminal fixes this, but it is a really sub-optimal fix.

**Comment by mislav** [comment] 2015-10-10 20:13
Closing because the problem likely existed in user's configuration and is not a bug with rbenv.

**Closed by mislav** 2015-10-10 20:13 UTC
