### ISSUE TITLE
Unresolved specs during Gem::Specification.reset:

### ISSUE THREAD

**Issue by rhuppert** [sstephenson/rbenv#726] opened 2015-04-30 03:58 UTC
I'm a bit unclear as to where my issue may be, but when I run annotate -r : 
```
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.7.7, ~> 1.7)
      minitest (~> 5.1)
```
When I run bin/annotate -r, no errors generated.

My path seems okay:
```
/home/ron/.rbenv/shims
:/home/ron/.rbenv/bin
:/.rbenv/plugins/ruby-build/bin
:/usr/local/heroku/bin
:./bin
:/usr/local/sbin
:/usr/local/bin
:/usr/sbin
:/usr/bin
:/sbin
:/bin
:/usr/games
:/usr/local/games
```
I'm running Rails 4.2.1 and Ruby 2.2.2 on Ubuntu 12.04.

It's all working, but I'm curious what is causing the error.

**Comment by ryanstout** [comment] 2015-05-13 19:59
I'm seeing a similar issue for another gem.  With rvm this works, but in rbenv I get the same warning.

**Comment by mislav** [comment] 2015-05-14 12:31
Is `annotate` some executable that comes from a gem within your Gemfile? Then `bin/annotate` or `bundle exec annotate` is the correct way to call it, because it takes your Gemfile into account. Just calling `annotate` activates the gem in a context outside of current project's gem bundle and might result in "unresolved specs" problem as you've experienced.

I don't think this is a problem with rbenv. Can I close this?

**Comment by ryanstout** [comment] 2015-05-14 17:10
@mislav So I'm actually using a different gem (volt framework that I'm developing), and the command if all I do in my command is:

```ruby
#!/usr/bin/env ruby

require 'bundler/setup'
```

I get the error.  This works fine in RVM.  I'm trying to set it up so my gem will work correctly even if someone forgets to use bundle exec (similar to how rails is used).  Any ideas?  Any context so I can figure it out myself would be great.  This is the full error I get:

```
WARN: Unresolved specs during Gem::Specification.reset:
      slop (~> 3.4)
      rack (~> 1.5.0)
      sprockets-sass (~> 1.0.0)
      sass (~> 3.2.5)
      listen (~> 2.8.0)
      uglifier (>= 2.4.0)
      configurations (~> 2.0.0.pre)
      therubyracer (>= 0)
      sprockets (< 3.0.0, >= 2.2.3)
      eventmachine (>= 0.12.0)
      websocket-driver (>= 0.5.1)
      bcrypt (~> 3.1.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```

What's really weird is if I patch rubygems and make Gem::Specification.reset a no-op, it takes 10x longer to boot bundler.  It might be a bundler issue, but I figured since it works fine on rvm (confirmed by myself and 4 people), and it fails on rbenv (confirmed by 5 people), I thought I would start with rbenv.

Thanks!

**Comment by ryanstout** [comment] 2015-05-14 17:11
I'm sure your busy, but if it helps, I can pair with you on this or something.  It would help me out a lot if I could figure out a work around or something.

**Comment by mislav** [comment] 2015-05-14 17:39
> and the command if all I do in my command is:

I'm sorry, you're going to have to be clearer about this. Did you say all your executables start with `require 'bundler/setup'`? What generated those executables? Where do they reside? Which executable name do you have problem with? Do you have the same problem with `bundle exec <foo>`?

I'm still not convinced that this is a rbenv issue.

**Comment by ryanstout** [comment] 2015-05-14 17:47
Sorry about that.  In my case this is for a gem I'm working on (gem's name is volt, at https://github.com/voltrb/volt )  The executable is bin/volt  Currently I have it setup a bit differently, but on my dev machine I have a locally installed gem with only the following in bin/volt

```ruby
#!/usr/bin/env ruby

require 'bundler/setup'
```

(thats the whole file)  And I've tested it with a ```puts``` in it to make sure I'm running the right file.
It works fine if I run it with ```bundle exec```
I'm the one who created the gem and the executable.  Once the gem is installed, the bin/volt file ends up at ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/volt-0.9.2/bin/volt

I'm happy to make a video if you want to see it in action :-)

**Comment by rhuppert** [comment] 2015-05-14 18:37
I'm out of the office. I will test it when I have a chance. Go ahead and close it. Thanks.

-------- Original message --------

**Comment by mislav** [comment] 2015-05-14 23:20
> but on my dev machine I have a locally installed gem with only the following in bin/volt

If you literally only have `require 'bundler/setup'` in `bin/volt`, how is it including volt library files and executing the CLI logic of your library?

> I'm happy to make a video if you want to see it in action :-)

A video would do little to help me debug this "issue". What would help me is a set of reproducible steps that demonstrate this problem using gems that are normally installed from RubyGems. I have to say I'm not terribly interested in your development setup for your volt library locally, because your setup can have a number of things wrong about it, and is not necessarily representative of a normal setup that a Ruby developer would have when installing RubyGems for their application.

I still need help understanding:

1. How is this issue caused by rbenv, a tool that only switches between Ruby versions and nothing more.
2. What scenario triggers this issue.

**Comment by mislav** [comment] 2015-10-10 17:47
Closing due to lack of info. Let me know if you still have problems.

**Closed by mislav** 2015-10-10 17:47 UTC
Labels: uncofirmed

**Comment by AlexLapin** [comment] 2015-11-18 22:59
You can run cleanup for your gems, for example:
gem cleanup json
gem cleanup minitest
...
