### ISSUE TITLE
Bundler requires 2.1.3?

### ISSUE THREAD

**Issue by sagikazarmark** [sstephenson/rbenv#668] opened 2014-12-16 20:39 UTC
I have rbenv installed with ruby 2.1.5.

When I try to install bundler: `gem install bundler` I get an error message:

rbenv: version `2.1.3' is not installed

It is not caused by the environment, because it happens on two different macines.

**Comment by sagikazarmark** [comment] 2015-01-01 02:39
Happy new year. :) It shows `2.1.5`.

**Comment by mislav** [comment] 2015-01-02 18:48
@sagikazarmark Happy new year as well. And I'm sorry; I asked you for the wrong thing. I meant the full output of `rbenv version` (singular).

**Comment by mislav** [comment] 2015-01-13 19:41
@sagikazarmark Bump. Let's get to the bottom of this and close this ticket if it's not a bug with rbenv itself.

**Comment by sagikazarmark** [comment] 2015-01-13 22:07
@mislav Strangely I can't reproduce it now. I would say close it for now, if pops up again, I will reopen it with more details.

**Comment by mislav** [comment] 2015-01-13 22:43
Alright thanks!

**Closed by mislav** 2015-01-13 22:43 UTC
Labels: uncofirmed
