### ISSUE TITLE
Incorrect error message "rbenv: version system is not installed" when calling non-existent system bundle command

### ISSUE THREAD

**Issue by theirishpenguin** [sstephenson/rbenv#770] opened 2015-08-27 08:58 UTC
This issue occurs where one project wants to use system ruby and another wants to use an rbenv specific version of ruby and bundler isn't installed for the system ruby.

### Expected result

Given I have a system ruby installed
**But I don't have the bundler gem installed for the system ruby**
And I have a different version of ruby installed via rbenv
And I cd to a Rails 4 project
And that project has a .ruby-version file that specifies 'system' as the ruby to use
When I run "bundle install"
Then I should get the message "bundle: command not found"
_Note: ruby -v in this project directory will appear to correctly state that system ruby is being used. The problem initially looks like this is not being propagated to the bundle command (which is the source of the confusion). That real problem being that bundler isn't installed for the system ruby._

### Actual result

I get the message
```
rbenv: version `system' is not installed (set by RBENV_VERSION environment variable)
```

### Workaround

This can be fixed by installing bundler for the system ruby...
```
rbenv shell system
gem install bundler # or sudo gem install bundler if neccessary
cd /to/your/rails4_project
bundle install # works!
```

**Platform**: Ubuntu with system ruby install via apt-get.

**Potential solution**: Perhaps in this case rbenv could check that the bundle command exists for system ruby - if not then say that in the error message.

**Comment by mislav** [comment] 2015-09-11 22:30
Is this problem the same if you update rbenv to the latest version from master?

Try `` cd `rbenv root` && git pull origin master ``

**Comment by mislav** [comment] 2015-10-10 17:31
Sorry, I can't reproduce this with newest version of rbenv. It must have been fixed in the meantime.

**Comment by pik** [comment] 2015-11-08 06:52
I am able to produce this - although I'm not sure how it could be handled better or whether it's a bug.

```
> which fluentd                                                                                                                                                                             
/Users/pik/.rbenv/shims/fluentd
> rbenv local 2.1.0
> fluentd                                                                                                                                                                                    
rbenv: fluentd: command not found

The `fluentd' command exists in these Ruby versions:
  2.2.3
```

Which is correct, on the other-hand if one goes to a directory where rbenv does not have permissions to create .ruby-version file. 

```
> cd /etc/fluent
> fluentd                                                                                                                                                                                         
rbenv: version `system' is not installed (set by RBENV_VERSION environment variable)
```

**Comment by mislav** [comment] 2015-11-09 03:18
Thanks; I was able to reproduce the original invalid message now. I'll try to fix the message to say something like "the `foo` command doesn't exist in system paths".

**Closed** 2015-11-14 10:42 UTC
Labels: unconfirmed
