### ISSUE TITLE
rbenv failed to set ruby version on OS X

### ISSUE THREAD

**Issue by AustinChou** [sstephenson/rbenv#763] opened 2015-08-04 09:44 UTC
There are two version of ruby on my system, system and 2.2.0.
I use `rbenv global system` to switch from current version back to system, but failed.
After this command, `ruby -v` still told me `ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]`
Which also I haved tried: 

- Disable `eval $"rbenv init -"`
- After `rbenv global system` run `rbenv rehash`

Nearly fresh machine with OS X Server installed, Yosemite 10.10.4. Used homebrew to install rbenv.

**Comment by mislav** [comment] 2015-08-04 10:16
`rbenv version` will tell you from where the version 2.2.0 is being set. It's probably from a local ruby-version file or from an environment variable. If it wasn't, your `rbenv global` change would have affected it.

**Comment by mislav** [comment] 2015-10-10 17:35
If you still have problems, please provide more info! Until then I'm closing this ticket. It's most likely not a bug in rbenv, but some bug in configuration/usage.

**Closed by mislav** 2015-10-10 17:35 UTC
